// Build-time artwork only: the shipped app uses embedded native icons and masks.
// Usage: node scripts/generate-icons.cjs [absolute path to sharp]
const fs = require('node:fs');
const path = require('node:path');
const sharp = require(process.argv[2] || 'sharp');
const root = path.resolve(__dirname, '..', 'assets');
const source = path.join(root, 'source');
const generated = path.join(root, 'generated');
fs.mkdirSync(source, { recursive: true });
fs.mkdirSync(generated, { recursive: true });

// An asymmetric feather with a curved vane, two open barbs and a long quill.
// The outline and shaft are shared by the sidebar logo and Windows app icon.
const feather = `<path fill="currentColor" d="M18.3 45.2C13.7 38.5 17.1 27 27.2 17.9C34.7 11.2 45.1 7.2 55 7C55 15.6 51.6 24.2 45.7 31L37.5 33.3L41.7 35.5C37.5 39.8 32.9 43 28.4 44.9L24 42.7L23.8 46.3C21.7 46.5 19.8 46.1 18.3 45.2Z"/><path d="M12 56C21.7 43.1 32.5 31.3 45.6 19.7" fill="none" stroke="currentColor" stroke-width="3.4" stroke-linecap="round"/>`;
// Cut the rachis from the plume while keeping the lower quill visible.
const featherMark = `<mask id="vane"><rect width="64" height="64" fill="white"/><path d="M19.5 46.3C27.6 36 36.1 27.2 45.6 19.7" fill="none" stroke="black" stroke-width="2.4" stroke-linecap="round"/></mask><g mask="url(#vane)">${feather}</g>`;
const svg = (body, view = 24, color = '#ffffff') => `<svg xmlns="http://www.w3.org/2000/svg" width="${view}" height="${view}" viewBox="0 0 ${view} ${view}" color="${color}">${body}</svg>`;
const stroke = body => `<g fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${body}</g>`;
const gear = [];
for (let i = 0; i < 6; i++) {
    for (const [offset, radius] of [[-30,7],[-18,7],[-12,9],[12,9],[18,7]]) {
        const a = (i * 60 + offset - 90) * Math.PI / 180;
        gear.push(`${(12 + Math.cos(a)*radius).toFixed(3)},${(12 + Math.sin(a)*radius).toFixed(3)}`);
    }
}
const assets = {
    feather: svg(featherMark, 64),
    processes: svg(stroke('<rect x="3.5" y="4" width="17" height="16" rx="2.5"/><path d="M7.5 9h9M7.5 15h9"/>')),
    performance: svg(stroke('<path d="M2.5 12h4l3-7.5 5 15 3-7.5h4"/>')),
    startup: svg(stroke('<path d="M7.6 5.3a8 8 0 1 0 8.8 0M12 2.8v9"/>')),
    services: svg(stroke(`<polygon points="${gear.join(' ')}"/><circle cx="12" cy="12" r="2.7"/>`)),
};
async function main() {
    // Render at the exact target pixel sizes. No stretch operation at runtime.
    const navSizes = [24,30,36,42,48,60,72,96];
    const logoSizes = [40,50,60,70,80,100,120,160];
    for (const [name, content] of Object.entries(assets)) {
        fs.writeFileSync(path.join(source, `${name}.svg`), content);
        for (const size of name === 'feather' ? logoSizes : navSizes) {
            const input = Buffer.from(content);
            const {data} = await sharp(input, {density: 384}).resize(size,size).ensureAlpha().raw().toBuffer({resolveWithObject:true});
            const mask = Buffer.alloc(size*size);
            for(let i=0; i<mask.length; i++) mask[i]=data[i*4+3];
            const runs=[];
            for(let i=0;i<mask.length;) {
                let count=1;
                while(count<255 && i+count<mask.length && mask[i+count]===mask[i]) count++;
                runs.push(count,mask[i]); i+=count;
            }
            fs.writeFileSync(path.join(generated, `${name}-${size}.rle`), Buffer.from(runs));
        }
    }
    fs.writeFileSync(path.join(generated,'masks.rs'), '// Generated by scripts/generate-icons.cjs.\n'+Object.keys(assets).map(name => `pub(super) const ${name.toUpperCase()}: &[(i32, &[u8])] = &[\n${(name==='feather'?logoSizes:navSizes).map(n=>`    (${n}, include_bytes!("${name}-${n}.rle")),`).join('\n')}\n];`).join('\n'));
    const app = svg(`<rect x="2" y="2" width="60" height="60" rx="14" fill="#2563EB"/><g transform="translate(3 1) scale(.88)" color="#ffffff">${featherMark}</g>`,64);
    fs.writeFileSync(path.join(source,'app.svg'),app);
    // PNG payload ICO works on all supported Windows versions. Every image has
    // its own pixel dimensions so Explorer never stretches a non-square mark.
    const sizes=[16,20,24,32,40,48,64,128,256];
    const images=[];
    for(const n of sizes) images.push(await sharp(Buffer.from(app),{density:768}).resize(n,n).png().toBuffer());
    const directory=Buffer.alloc(6+16*sizes.length); directory.writeUInt16LE(1,2); directory.writeUInt16LE(sizes.length,4);
    let offset=directory.length;
    sizes.forEach((n,i)=>{const b=6+i*16; directory[b]=n===256?0:n; directory[b+1]=directory[b]; directory.writeUInt16LE(1,b+4); directory.writeUInt16LE(32,b+6); directory.writeUInt32LE(images[i].length,b+8); directory.writeUInt32LE(offset,b+12); offset+=images[i].length;});
    fs.writeFileSync(path.join(root,'app.ico'),Buffer.concat([directory,...images]));
    await sharp(Buffer.from(app),{density:384}).resize(256,256).png().toFile(path.join(root,'app.png'));
    // A design sheet for inspection; it is not used by the application.
    const tiles=[];
    for(const [i,name] of Object.keys(assets).entries()) {
        const rendered=assets[name].replace('color="#ffffff"','color="#B8C9E3"');
        tiles.push({input:await sharp(Buffer.from(rendered),{density:384}).resize(80,80).png().toBuffer(),left:30+i*120,top:40});
    }
    await sharp({create:{width:640,height:160,channels:4,background:'#152036'}}).composite(tiles).png().toFile(path.join(root,'icon-sheet.png'));
}
main().catch(e=>{console.error(e);process.exitCode=1;});
